### ISSUE TITLE
シミュレータとビルド環境の配布方法を決定する

### ISSUE THREAD

**Issue by sho-hama** [LED-Camp/LED-Camp9#1]
Wikiにmdで記入すること

- [x] wiki作成
- [ ] 以下の中からどれを採用するのかを決定する
  - Windows + WSL
  - Windows + Virtualbox
  - Windows直

**Comment by ken551** [comment]
Webotsを使ってもらうことに決定したので（Win版Webotsはコンパイラ付属）Closeします
