### ISSUE TITLE
LEDTankのバイナリとシミュレータの間の通信方法を決定する

### ISSUE THREAD

**Issue by tomohiro-iwa** [LED-Camp/LED-Camp9#2]
**開発チームにて、通信や動的リンクではなく、一体バイナリビルドの実施が容易と議論により合意して完了**

## 各技術の調査
- [ ] ROS
- [ ] DLL
- [ ] MQTT
- [ ] その他
## meeting
- [ ] 合意形成

**Comment by ken551** [comment]
Webotsを用いた一括ビルドの方針に変更したのでCloseします
