### ISSUE TITLE
実験用と本番用のコードが混ざっている

### ISSUE THREAD

**Issue by sho-hama** [LED-Camp/LED-Camp9#28]
LED-Camp7ではmakefile内で`-D EXPERIMENTAL_USE`を付加することによってコード内でデバッグモードと本番モードを切り替えていたが、LED-Cmap9からはステートマシン図を分けることで実現するようにしたのでこの分岐は不要。

コードの見通しも悪くなるので分岐を消したい。

**Comment by ken551** [comment]
#32 をマージしたのでCloseします
