### ISSUE TITLE
生成ファイルの場所を分ける

### ISSUE THREAD

**Issue by ken551** [LED-Camp/LED-Camp9#36]
`controllers/main_sim`直下は，用意してあるコードとastah\*から吐き出されるコードが混在していて，あまりよくないように思われます

`generated_files`的なフォルダを作って，自動生成のファイルはすべてそちらに行くようにするべきではないでしょうか？

**Comment by yosuke-kirihata** [comment]
指摘、提案に同意です。ただ、現状どうしても回避しないといけないということはないので、優先度最低かなと思います。

**Comment by sho-hama** [comment]
直前すぎてリスク高いので今回はしない
