### ISSUE TITLE
シミュレータのプロトタイプ（最低限）の設計を検討するシミュレータを設計する

### ISSUE THREAD

**Issue by yosuke-kirihata** [LED-Camp/LED-Camp9#4]
- [ ] たたき台の図を作成して、疑問出し
完了条件：開発メンバーの疑問が解決されればDone
- [x] astahとwebotを使ったユースケースを考える
- [ ] シミュレータ/実機用で手始めにモータ駆動APIの最上層クラス(TwinWeelDriver)を作成し、実装部分のスイッチングを簡潔にできるようにする
- [ ] Webotsでセンサ設定パラメータをどのように決定すれば良いか
- [ ] Webotsでカラーセンサ実装できる？
## 疑問
simLoopの間隔は調整できるのか調査

**Comment by ken551** [comment]
タスクとしてはできていると思うのでCloseします
