### ISSUE TITLE
テンプレート内変数初期化の対応

### ISSUE THREAD

**Issue by ken551** [LED-Camp/LED-Camp9#46]
モデルの属性にint以外を指定した場合，おそらく初期化コードがうまく生成されない
https://github.com/LED-Camp/LED-Camp9/commit/d61788b92132230df70b988d454d47a9c223d784#r55415990

float, double, unsigned intなどほかのデータ型についても同様に初期化処理を入れるようにする
（ただ，モデル内で値に代入することを想定すれば最悪なくても・・・？）

**Comment by tomohiro-iwa** [comment]
astah\* APIのIClassにisPrimitiveType()というメソッドが有りました。
astah\* APIDocumentの記載漏れだったようなので、このメソッド使って修正しておきます
