### ISSUE TITLE
センサ値の出力をOFFにしたくてもできない

### ISSUE THREAD

**Issue by ken551** [LED-Camp/LED-Camp9#47]
デフォルトでセンサの値をコンソールに出力するようにしていますが，毎ループで表示されるので状態遷移時の情報が見にくいのでは？と思いました．

#defineとかで出力ON/OFFの切り替えができればいいかなとか思いましたが，コード直接触ってもらうことにもなるのでややこくなる気もします．

**Comment by sho-hama** [comment]
そこまでログの量は多くないので、僕は1つのAPIにまとめる派です！

**Comment by ken551** [comment]
#53 で対応したのでCloseします
